### ISSUE TITLE
cryptodev-linux tests Incompatible with openssl 1.1

### ISSUE THREAD

**Issue by kanavin** [cryptodev-linux/cryptodev-linux#22]
| openssl_wrapper.c:27:11: error: field 'hmac' has incomplete type
|   HMAC_CTX hmac;
|            ^~~~
| openssl_wrapper.c:28:13: error: field 'md' has incomplete type
|   EVP_MD_CTX md;
|              ^~
| openssl_wrapper.c: In function 'remove_mapping':
| openssl_wrapper.c:68:3: warning: implicit declaration of function 'HMAC_CTX_cleanup' [-Wimplicit-function-declaration]
|    HMAC_CTX_cleanup(&mapping->ctx.hmac);
|    ^~~~~~~~~~~~~~~~
| openssl_wrapper.c:72:3: warning: implicit declaration of function 'EVP_MD_CTX_cleanup' [-Wimplicit-function-declaration]
|    EVP_MD_CTX_cleanup(&mapping->ctx.md);
|    ^~~~~~~~~~~~~~~~~~
| openssl_wrapper.c: In function 'openssl_hmac':
| openssl_wrapper.c:133:3: warning: implicit declaration of function 'HMAC_CTX_init' [-Wimplicit-function-declaration]
|    HMAC_CTX_init(ctx);
|    ^~~~~~~~~~~~~

**Comment by cristian-stoica** [comment]
OpenSSL 1.1.0 API change: 
* HMAC_CTX_init has been replaced by HMAC_CTX_reset  (OpenSSL: a87a0a6e5eb7993ae7a4d2eb13e605d8b5428073)
* HMAC_CTX_cleanup was removed (OpenSSL 32fd54a9a36c172cf4e5fe4b7af2ae1f1ce1bc0a)
* EVP_MD_CTX_cleanup was removed (OpenSSL 74cabf3fef77ab73c45e27cf6ed90f6db020e7c7)
