### ISSUE TITLE
compilation warning with openssl 1.1.0f

### ISSUE THREAD

**Issue by riggy2013** [cryptodev-linux/cryptodev-linux#25]
Hi, 

I got below warnings in compilation with openssl 1.1.0f:

> crypto/engine/eng_cryptodev.c: In function 'get_cryptodev_ciphers':
> crypto/engine/eng_cryptodev.c:321:14: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      sess.key = (caddr_t) "123456789abcdefghijklmno";
>               ^
> crypto/engine/eng_cryptodev.c: In function 'get_cryptodev_digests':
> crypto/engine/eng_cryptodev.c:360:17: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      sess.mackey = (caddr_t) "123456789abcdefghijklmno";
>                  ^
> crypto/engine/eng_cryptodev.c: In function 'cryptodev_cipher':
> crypto/engine/eng_cryptodev.c:451:14: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      cryp.src = (caddr_t) in;
>               ^
> crypto/engine/eng_cryptodev.c:452:14: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      cryp.dst = (caddr_t) out;
>               ^
> crypto/engine/eng_cryptodev.c:458:17: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>          cryp.iv = (caddr_t) EVP_CIPHER_CTX_iv(ctx);
>                  ^
> crypto/engine/eng_cryptodev.c: In function 'cryptodev_init_key':
> crypto/engine/eng_cryptodev.c:511:15: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      sess->key = (caddr_t) key;
>                ^
> crypto/engine/eng_cryptodev.c: In function 'cryptodev_digest_init':
> crypto/engine/eng_cryptodev.c:913:18: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      sess->mackey = state->dummy_mac_key;
>                   ^
> crypto/engine/eng_cryptodev.c: In function 'cryptodev_digest_update':
> crypto/engine/eng_cryptodev.c:966:14: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      cryp.src = (caddr_t) data;
>               ^
> crypto/engine/eng_cryptodev.c:968:14: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      cryp.mac = (caddr_t) state->digest_res;
>               ^
> crypto/engine/eng_cryptodev.c: In function 'cryptodev_digest_final':
> crypto/engine/eng_cryptodev.c:995:18: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>          cryp.src = state->mac_data;
>                   ^
> crypto/engine/eng_cryptodev.c:997:18: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>          cryp.mac = (caddr_t) md;
>                   ^
> crypto/engine/eng_cryptodev.c: In function 'cryptodev_digest_copy':
> crypto/engine/eng_cryptodev.c:1057:18: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      sess->mackey = dstate->dummy_mac_key;
>                   ^
> crypto/engine/eng_cryptodev.c: In function 'bn2crparam':
> crypto/engine/eng_cryptodev.c:1225:16: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      crp->crp_p = (caddr_t) b;
>                 ^
> crypto/engine/eng_cryptodev.c: In function 'cryptodev_dsa_do_sign':
> crypto/engine/eng_cryptodev.c:1493:28: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      kop.crk_param[0].crp_p = (caddr_t) dgst;
>                             ^
> crypto/engine/eng_cryptodev.c: In function 'cryptodev_dsa_verify':
> crypto/engine/eng_cryptodev.c:1540:28: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      kop.crk_param[0].crp_p = (caddr_t) dgst;
>                             ^
> crypto/engine/eng_cryptodev.c: In function 'cryptodev_dh_compute_key':
> crypto/engine/eng_cryptodev.c:1616:28: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
>      kop.crk_param[3].crp_p = (caddr_t) key;

They seems related to the patches in 

http://rt.openssl.org/Ticket/Display.html?id=2770&user=guest&pass=guest

However, those old patches can't work with openssl 1.1.0f. Any update? Do i still need new patch?

Thanks,

riggy2013

**Comment by cristian-stoica** [comment]
@riggy2013 The original patches were meant for the OpenSSL of that time. OpenSSL code has changed enough in the meantime that the patches will probably not apply cleanly - especially on the 1.1.0 branch.
However, since these warnings are for the OpenSSL codebase, a good idea is to report the issue to them or, better yet, submit them a patch.
