### ISSUE TITLE
error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]

### ISSUE THREAD

**Issue by gallatin1988** [cryptodev-linux/cryptodev-linux#29]
Got the below message when trying to build with gentoo with linux kernel 4.12.9 through kernel 4.13.2 and gcc 6.4

>>> Emerging (1 of 1) sys-kernel/cryptodev-1.9::gentoo
 * cryptodev-linux-1.9.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                                                           [ ok ]
 * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found kernel object directory:
 *     /lib/modules/4.13.2-gentoo/build
 * Found sources for kernel version:
 *     4.13.2-gentoo
 * Checking for suitable kernel configuration options...                                                                                                                                                     [ ok ]
>>> Unpacking source...
>>> Unpacking cryptodev-linux-1.9.tar.gz to /var/tmp/portage/sys-kernel/cryptodev-1.9/work
>>> Source unpacked in /var/tmp/portage/sys-kernel/cryptodev-1.9/work
>>> Preparing source in /var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9 ...
ln: failed to create symbolic link 'Module.symvers': File exists
 * Preparing cryptodev module
make -j5 HOSTCC=x86_64-pc-linux-gnu-gcc CROSS_COMPILE=x86_64-pc-linux-gnu- 'LDFLAGS=-m elf_x86_64' build 
make -C /usr/src/linux M=/var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9 ARCH=x86 CROSS_COMPILE=x86_64-pc-linux-gnu- modules
make[1]: Entering directory '/usr/src/linux-4.13.2-gentoo'
  CC [M]  /var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/ioctl.o
  CC [M]  /var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/main.o
  CC [M]  /var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/cryptlib.o
  CC [M]  /var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/authenc.o
  CC [M]  /var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/zc.o
/var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/ioctl.c:1127:3: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  {0, },
   ^
/var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/ioctl.c:1127:3: note: (near initialization for ‘verbosity_ctl_dir[1]’)
/var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/ioctl.c:1136:3: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  {0, },
   ^
/var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/ioctl.c:1136:3: note: (near initialization for ‘verbosity_ctl_root[1]’)
  CC [M]  /var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/util.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:302: /var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9/ioctl.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1512: _module_/var/tmp/portage/sys-kernel/cryptodev-1.9/work/cryptodev-linux-1.9] Error 2
make[1]: Leaving directory '/usr/src/linux-4.13.2-gentoo'
make: *** [Makefile:27: build] Error 2
 * ERROR: sys-kernel/cryptodev-1.9::gentoo failed (compile phase):
 *   emake failed

**Comment by cristian-stoica** [comment]
fixed in f0d69774afb27ffc62bf353465fba145e70cb85a
