### ISSUE TITLE
Cryptodev built-in instead of loadable module

### ISSUE THREAD

**Issue by jmbents** [cryptodev-linux/cryptodev-linux#40]
I am working on a project that is not allowed to use loadable modules but we would still like to use cryptodev to offload to the sec engine.  Is there a limitation that caused cryptodev to only be able to be used as a loadable module instead of built-in?

**Comment by horiag** [comment]
The limitation is due to cryptodev-linux not being accepted officially in Linux kernel, the only option thus being an out-of-tree module.
Of course, as Cristian mentioned, it could "unofficially" be added in the Linux kernel tree and built as needed.

**Comment by jmbents** [comment]
Ok, thank you for the feedback
