### ISSUE TITLE
OpenSSL patch website cannot be opened, where to find the patch please?

### ISSUE THREAD

**Issue by Yogurt2019** [cryptodev-linux/cryptodev-linux#62]
I want to use cryptodev to accelerate my OpenSSL ciphers, but I can't open the website of the latest patch of OpenSSL in readme, where to find the patch please?
Thx for any help.

**Comment by yegorich** [comment]
Should this link be removed from the `README` file?

**Comment by cristian-stoica** [comment]
Probably; rewording of the README may also be appropriate.
