### ISSUE TITLE
3.17.6 throws a conflicting definition error on make

### ISSUE THREAD

**Issue by sempervictus** [cryptodev-linux/cryptodev-linux#7]
When attempting to build against 3.17.6, we're seeing redefinition errors on sg_copy calls - at first glance it looks like the API changed and call param order was swapped.

```
make -C /lib/modules/3.17.6-i7/build SUBDIRS=`pwd` modules
make[1]: Entering directory `/usr/src/linux-headers-3.17.6-i7'
  CC [M]  /opt/build/cryptodev-linux/authenc.o
In file included from /opt/build/cryptodev-linux/authenc.c:46:0:
/opt/build/cryptodev-linux/util.h:1:5: error: conflicting types for ‘sg_copy’
 int sg_copy(struct scatterlist *sg_from, struct scatterlist *sg_to, int len);
     ^
In file included from include/linux/dmaengine.h:28:0,
                 from include/linux/skbuff.h:31,
                 from include/crypto/algapi.h:18,
                 from include/crypto/scatterwalk.h:20,
                 from /opt/build/cryptodev-linux/authenc.c:42:
include/linux/scatterlist.h:253:5: note: previous declaration of ‘sg_copy’ was here
 int sg_copy(struct scatterlist *dst_sg, struct scatterlist *src_sg,
     ^
make[2]: *** [/opt/build/cryptodev-linux/authenc.o] Error 1
make[1]: *** [_module_/opt/build/cryptodev-linux] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.17.6-i7'
make: *** [build] Error 2
```

**Comment by n0-1** [comment]
Hi,

On Fri, Feb 13, 2015 at 12:54:43PM -0800, RageLtMan wrote:
> When attempting to build against 3.17.6, we're seeing redefinition errors on sg_copy calls - at first glance it looks like the API changed and call param order was swapped.
> 
> ```
> make -C /lib/modules/3.17.6-i7/build SUBDIRS=`pwd` modules
> make[1]: Entering directory `/usr/src/linux-headers-3.17.6-i7'
>   CC [M]  /opt/build/cryptodev-linux/authenc.o
> In file included from /opt/build/cryptodev-linux/authenc.c:46:0:
> /opt/build/cryptodev-linux/util.h:1:5: error: conflicting types for ‘sg_copy’
>  int sg_copy(struct scatterlist *sg_from, struct scatterlist *sg_to, int len);
>      ^
> In file included from include/linux/dmaengine.h:28:0,
>                  from include/linux/skbuff.h:31,
>                  from include/crypto/algapi.h:18,
>                  from include/crypto/scatterwalk.h:20,
>                  from /opt/build/cryptodev-linux/authenc.c:42:
> include/linux/scatterlist.h:253:5: note: previous declaration of ‘sg_copy’ was here
>  int sg_copy(struct scatterlist *dst_sg, struct scatterlist *src_sg,
>      ^
> make[2]: *** [/opt/build/cryptodev-linux/authenc.o] Error 1
> make[1]: *** [_module_/opt/build/cryptodev-linux] Error 2
> make[1]: Leaving directory `/usr/src/linux-headers-3.17.6-i7'
> make: *** [build] Error 2
> ```

Scatterlist.h of 3.17.6 does not have a prototype named 'sg_copy'. You
probably run a patched kernel. The function in question has been added
to cryptodev-linux after extracting it from a patch sent to LKML (see:
https://lkml.org/lkml/2011/1/17/258). Maybe you have that one applied to
your kernel?

Cheers, Phil

**Comment by n0-1** [comment]
Closing due to missing feedback. Feel free to reopen in case you are still affected by this issue.
