### ISSUE TITLE
pgcrypto to use cryptodev

### ISSUE THREAD

**Issue by pymenow** [cryptodev-linux/cryptodev-linux#72]
Hi,

Is there any reference on having [pgcrypto ](https://www.postgresql.org/docs/9.4/pgcrypto.html)to use cryptodev on an embedded system ?

**Comment by cristian-stoica** [comment]
Openssl (that pgcrypto seems to be using) will use cryptodev automatically (and more or less transparently) if it is build with -DHAVE_CRYPTODEV. At least that was the case on OpenSSL < 1.0; it shouldn't be much different today but I don't have a clean-cut answer.

**Comment by pymenow** [comment]
Perfect thanks . have openssl using cryptodev .
Didn't realise pgcrypto used openssl.
